language: node_js
node_js:
  - 13

services:
  - docker

# Pre-testing installs
install:
  - echo "nothing needs to be installed"

# Scripts to be run such as tests
before_script:
  - echo "no tests"

script:
  - docker --version # print the version for logging
  - docker build -t peracc000/udagram-api-feed:v2 ./project/udagram-api-feed
  - docker build -t peracc000/udagram-api-user:v1 ./project/udagram-api-user
  - docker build -t peracc000/udagram-frontend:v2 ./project/udagram-frontend
  - docker build -t peracc000/reverseproxy:v1 ./project/udagram-reverseproxy

after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push peracc000/udagram-api-feed:v2
  - docker push peracc000/udagram-api-user:v1
  - docker push peracc000/udagram-frontend:v2
  - docker push peracc000/reverseproxy:v1