apiVersion: apps/v1
kind: Deployment
metadata:
  name: feed-deployment
  labels:
    app: feed-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: feed
  template:
    metadata:
      labels:
        app: feed
    spec:
      containers:
      - name: feed
        image: peracc000/udagram-api-feed:v3
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"  
        ports:
        - containerPort: 8080
        envFrom:
          - configMapRef: 
              name: udagram-config-map
          - secretRef:
              name: udagram-secret
          - secretRef:
              name: aws-secret